package dev.zeropng.essentialscore.gui;

public enum MenuType {
    MAIN, TELEPORT, HOME, HOME_DELETE, PLAYER_SELECT_TPA, PLAYER_SELECT_TPAHERE,
    REQUESTS, RANK_INFO, RANK_LIST, RANK_EDIT, RANK_DELETE, RANK_PLAYERS, RANK_ASSIGN,
    PETS, WARP, HELP, ADMIN, ADMIN_HOME, ADMIN_TPA, ADMIN_PET,
    ADMIN_WARP, ADMIN_EXPERIMENTAL, WARP_EDIT, WARP_DELETE
}
